export const AI_MANAGER_ACCOUNT_SELECT = {
  id: true,
  creatorProfileId: true,
  status: true,
  displayName: true,
  slug: true,
  avatarAssetUrl: true,
  intro: true,
  archetype: true,
  publicVisibility: true,
  primaryLanguage: true,
  tone: true,
  supportStyle: true,
  disclosurePolicy: true,
  managerActivityWalletAddress: true,
  budgetWalletAddress: true,
  specialties: true,
  forbiddenTopics: true,
  brandGuardrails: true,
  createdAt: true,
  updatedAt: true,
  billingPolicy: {
    select: {
      status: true,
      billingMode: true,
      preferredRail: true,
      currency: true,
      freeTierEnabled: true,
      freeTierScope: true,
      autoPayEnabled: true,
      monthlyJpycCap: true,
      dailyJpycCap: true,
      perActionJpycCap: true,
      allowedBillableCapabilities: true,
      pausedAt: true,
      pauseReason: true,
    },
  },
  budgetBalance: {
    select: {
      currency: true,
      availableAmount: true,
      reservedAmount: true,
      updatedAt: true,
    },
  },
  usageRecords: {
    orderBy: {
      createdAt: "desc",
    },
    take: 8,
    select: {
      id: true,
      capability: true,
      provider: true,
      model: true,
      currency: true,
      chargeAmount: true,
      providerCostUsd: true,
      platformFeeUsd: true,
      totalChargeUsd: true,
      billingState: true,
      failureReason: true,
      createdAt: true,
      agentTask: {
        select: {
          taskType: true,
        },
      },
      paymentAttempts: {
        orderBy: {
          createdAt: "desc",
        },
        take: 1,
        select: {
          id: true,
          rail: true,
          status: true,
          payerWalletAddress: true,
          currency: true,
          amount: true,
          txHash: true,
          payeeWalletAddress: true,
          failureReason: true,
          createdAt: true,
          confirmedAt: true,
        },
      },
    },
  },
  budgetTransactions: {
    orderBy: {
      createdAt: "desc",
    },
    take: 5,
    select: {
      id: true,
      direction: true,
      transactionType: true,
      currency: true,
      amount: true,
      resultingAvailableAmount: true,
      note: true,
      actorAddress: true,
      createdAt: true,
    },
  },
  fundingEvidences: {
    orderBy: {
      createdAt: "desc",
    },
    take: 5,
    select: {
      id: true,
      status: true,
      chainId: true,
      currency: true,
      amount: true,
      txHash: true,
      fromWalletAddress: true,
      toWalletAddress: true,
      reportedByAddress: true,
      note: true,
      createdAt: true,
      matchedAt: true,
      matchedBudgetTransactionId: true,
    },
  },
  paymentAttemptEvents: {
    orderBy: {
      createdAt: "desc",
    },
    take: 100,
    select: {
      id: true,
      source: true,
      eventType: true,
      status: true,
      txHash: true,
      detail: true,
      createdAt: true,
      paymentAttempt: {
        select: {
          id: true,
          rail: true,
          usageRecord: {
            select: {
              id: true,
              capability: true,
              agentTask: {
                select: {
                  taskType: true,
                },
              },
            },
          },
        },
      },
    },
  },
} as const;
