import assert from "node:assert/strict";
import test from "node:test";

import { deriveAiManagerPendingX402Queue } from "../lib/aiManager/pendingQueue";
import { deriveAiManagerX402ActivityTimeline } from "../lib/aiManager/x402Timeline";
import type { SerializedAiManagerAccount } from "../lib/serializers/aiManager";

test("deriveAiManagerPendingX402Queue returns pending x402 items only", () => {
  const account: SerializedAiManagerAccount = {
    id: "manager-1",
    creatorProfileId: "1",
    ownerControlWalletAddress: null,
    status: "ACTIVE",
    displayName: "Luna",
    slug: "luna",
    avatarAssetUrl: null,
    intro: null,
    archetype: "PROMOTER",
    publicVisibility: "OWNER_ONLY",
    primaryLanguage: "ja",
    tone: "FRIENDLY",
    supportStyle: "PROMOTIONAL",
    disclosurePolicy: "ALWAYS_DISCLOSE_AI",
    managerActivityWalletAddress: null,
    budgetWalletAddress: null,
    specialties: [],
    forbiddenTopics: [],
    brandGuardrails: [],
    createdAt: "2026-03-29T00:00:00.000Z",
    updatedAt: "2026-03-29T00:00:00.000Z",
    billingPolicy: null,
    budgetBalance: null,
    recentUsageRecords: [
      {
        id: "usage-1",
        capability: "POST_DRAFTING",
        provider: "openai",
        model: null,
        taskType: "ANNOUNCEMENT_DRAFT",
        currency: "JPYC",
        chargeAmount: "100",
        providerCostUsd: "0.1",
        platformFeeUsd: "0.1",
        totalChargeUsd: "0.2",
        billingState: "PAYMENT_PENDING",
        failureReason: null,
        createdAt: "2026-03-29T12:00:00.000Z",
        latestPaymentAttempt: {
          id: "attempt-1",
          rail: "X402",
          status: "PENDING",
          payerWalletAddress: "0x1111111111111111111111111111111111111111",
          currency: "JPYC",
          amount: "100",
          txHash: null,
          payeeWalletAddress: "0x2222222222222222222222222222222222222222",
          failureReason: null,
          createdAt: "2026-03-29T12:00:00.000Z",
          confirmedAt: null,
        },
      },
      {
        id: "usage-2",
        capability: "WEB_RESEARCH",
        provider: "openai",
        model: null,
        taskType: "ANALYZE",
        currency: "JPYC",
        chargeAmount: "80",
        providerCostUsd: "0.1",
        platformFeeUsd: "0.1",
        totalChargeUsd: "0.2",
        billingState: "SETTLED",
        failureReason: null,
        createdAt: "2026-03-29T11:00:00.000Z",
        latestPaymentAttempt: {
          id: "attempt-2",
          rail: "X402",
          status: "CONFIRMED",
          payerWalletAddress: null,
          currency: "JPYC",
          amount: "80",
          txHash:
            "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          payeeWalletAddress: null,
          failureReason: null,
          createdAt: "2026-03-29T11:00:00.000Z",
          confirmedAt: "2026-03-29T11:05:00.000Z",
        },
      },
    ],
    recentBudgetTransactions: [],
    recentFundingEvidences: [],
    recentPaymentAttemptEvents: [
      {
        id: "event-1",
        paymentAttemptId: "attempt-1",
        usageId: "usage-1",
        source: "BILLING_SYSTEM",
        eventType: "ATTEMPT_CREATED",
        status: "PENDING",
        rail: "X402",
        capability: "POST_DRAFTING",
        taskType: "ANNOUNCEMENT_DRAFT",
        txHash: null,
        detail: "x402 settlement pending callback.",
        createdAt: "2026-03-29T12:01:00.000Z",
      },
    ],
    reconciliation: {
      pendingX402Count: 1,
      pendingX402Amount: "100",
      oldestPendingX402CreatedAt: "2026-03-29T12:00:00.000Z",
      pendingX402DeliveryStatus: "ACTIVE",
      pendingX402DeliveryHint: "connector callback 待ちの範囲です。",
      latestPendingX402EventAt: null,
      latestPendingX402EventSource: null,
      latestPendingX402EventType: null,
      failedX402Count: 0,
      failedX402Amount: "0",
      unmatchedFundingEvidenceCount: 0,
      unmatchedFundingEvidenceAmount: "0",
      latestConfirmedX402At: null,
      recoveryCount: 0,
      latestRecoveryLabel: null,
      latestRecoverySourceLabel: null,
      latestRecoveryCreatedAt: null,
      recoveryConnectorCount: 0,
      recoveryOwnerReviewCount: 0,
      recoveryBillingSystemCount: 0,
      requiresAttention: true,
    },
  };

  const queue = deriveAiManagerPendingX402Queue(account);

  assert.equal(queue.length, 1);
  assert.deepEqual(queue[0], {
    usageId: "usage-1",
    paymentAttemptId: "attempt-1",
    capability: "POST_DRAFTING",
    capabilityLabel: "投稿下書き",
    taskType: "ANNOUNCEMENT_DRAFT",
    taskLabel: "告知文案を作る",
    amount: "100",
    currency: "JPYC",
    createdAt: "2026-03-29T12:00:00.000Z",
    payerWalletAddress: "0x1111111111111111111111111111111111111111",
    payeeWalletAddress: "0x2222222222222222222222222222222222222222",
    deliveryStatus: "STALE",
    deliveryHint: "最後の billing system event から長時間更新がありません。connector と owner review の両方を確認してください。",
    lastEventLabel: "settlement started",
    lastEventSourceLabel: "billing system",
    lastEventAt: "2026-03-29T12:01:00.000Z",
    lastEventDetail: "x402 settlement pending callback.",
  });
});

test("deriveAiManagerPendingX402Queue uses latest delivery event recency for delivery status", () => {
  const now = Date.now();
  const attemptCreatedAt = new Date(now - 2 * 60 * 60 * 1000).toISOString();
  const latestEventAt = new Date(now - 5 * 60 * 1000).toISOString();

  const queue = deriveAiManagerPendingX402Queue({
    id: "manager-1",
    creatorProfileId: "1",
    ownerControlWalletAddress: null,
    status: "ACTIVE",
    displayName: "Luna",
    slug: "luna",
    avatarAssetUrl: null,
    intro: null,
    archetype: "PROMOTER",
    publicVisibility: "OWNER_ONLY",
    primaryLanguage: "ja",
    tone: "FRIENDLY",
    supportStyle: "PROMOTIONAL",
    disclosurePolicy: "ALWAYS_DISCLOSE_AI",
    managerActivityWalletAddress: null,
    budgetWalletAddress: null,
    specialties: [],
    forbiddenTopics: [],
    brandGuardrails: [],
    createdAt: "2026-03-29T00:00:00.000Z",
    updatedAt: "2026-03-29T00:00:00.000Z",
    billingPolicy: null,
    budgetBalance: null,
    recentUsageRecords: [
      {
        id: "usage-1",
        capability: "WEB_RESEARCH",
        provider: "openai",
        model: null,
        taskType: "ANALYZE",
        currency: "JPYC",
        chargeAmount: "100",
        providerCostUsd: "0.1",
        platformFeeUsd: "0.1",
        totalChargeUsd: "0.2",
        billingState: "PAYMENT_PENDING",
        failureReason: null,
        createdAt: attemptCreatedAt,
        latestPaymentAttempt: {
          id: "attempt-1",
          rail: "X402",
          status: "PENDING",
          payerWalletAddress: null,
          currency: "JPYC",
          amount: "100",
          txHash: null,
          payeeWalletAddress: null,
          failureReason: null,
          createdAt: attemptCreatedAt,
          confirmedAt: null,
        },
      },
    ],
    recentBudgetTransactions: [],
    recentFundingEvidences: [],
    recentPaymentAttemptEvents: [
      {
        id: "event-1",
        paymentAttemptId: "attempt-1",
        usageId: "usage-1",
        source: "X402_CONNECTOR",
        eventType: "ATTEMPT_CREATED",
        status: "PENDING",
        rail: "X402",
        capability: "WEB_RESEARCH",
        taskType: "ANALYZE",
        txHash: null,
        detail: "connector received request",
        createdAt: latestEventAt,
      },
    ],
    reconciliation: {
      pendingX402Count: 1,
      pendingX402Amount: "100",
      oldestPendingX402CreatedAt: attemptCreatedAt,
      pendingX402DeliveryStatus: "ACTIVE",
      pendingX402DeliveryHint: null,
      latestPendingX402EventAt: latestEventAt,
      latestPendingX402EventSource: "X402_CONNECTOR",
      latestPendingX402EventType: "ATTEMPT_CREATED",
      failedX402Count: 0,
      failedX402Amount: "0",
      unmatchedFundingEvidenceCount: 0,
      unmatchedFundingEvidenceAmount: "0",
      latestConfirmedX402At: null,
      recoveryCount: 0,
      latestRecoveryLabel: null,
      latestRecoverySourceLabel: null,
      latestRecoveryCreatedAt: null,
      recoveryConnectorCount: 0,
      recoveryOwnerReviewCount: 0,
      recoveryBillingSystemCount: 0,
      requiresAttention: true,
    },
  });

  assert.equal(queue[0]?.deliveryStatus, "ACTIVE");
  assert.equal(
    queue[0]?.deliveryHint,
    "x402 connector から最近 event が届いています。callback 継続待ちの範囲です。"
  );
});

test("deriveAiManagerX402ActivityTimeline sorts x402 events by latest event time", () => {
  const timeline = deriveAiManagerX402ActivityTimeline({
    id: "manager-1",
    creatorProfileId: "1",
    ownerControlWalletAddress: null,
    status: "ACTIVE",
    displayName: "Luna",
    slug: "luna",
    avatarAssetUrl: null,
    intro: null,
    archetype: "PROMOTER",
    publicVisibility: "OWNER_ONLY",
    primaryLanguage: "ja",
    tone: "FRIENDLY",
    supportStyle: "PROMOTIONAL",
    disclosurePolicy: "ALWAYS_DISCLOSE_AI",
    managerActivityWalletAddress: null,
    budgetWalletAddress: null,
    specialties: [],
    forbiddenTopics: [],
    brandGuardrails: [],
    createdAt: "2026-03-29T00:00:00.000Z",
    updatedAt: "2026-03-29T00:00:00.000Z",
    billingPolicy: null,
    budgetBalance: null,
    recentUsageRecords: [
      {
        id: "usage-1",
        capability: "POST_DRAFTING",
        provider: "openai",
        model: null,
        taskType: "ANNOUNCEMENT_DRAFT",
        currency: "JPYC",
        chargeAmount: "100",
        providerCostUsd: "0.1",
        platformFeeUsd: "0.1",
        totalChargeUsd: "0.2",
        billingState: "PAYMENT_PENDING",
        failureReason: null,
        createdAt: "2026-03-29T12:00:00.000Z",
        latestPaymentAttempt: {
          id: "attempt-1",
          rail: "X402",
          status: "PENDING",
          payerWalletAddress: null,
          currency: "JPYC",
          amount: "100",
          txHash: null,
          payeeWalletAddress: null,
          failureReason: null,
          createdAt: "2026-03-29T12:00:00.000Z",
          confirmedAt: null,
        },
      },
      {
        id: "usage-2",
        capability: "WEB_RESEARCH",
        provider: "openai",
        model: null,
        taskType: "ANALYZE",
        currency: "JPYC",
        chargeAmount: "80",
        providerCostUsd: "0.1",
        platformFeeUsd: "0.1",
        totalChargeUsd: "0.2",
        billingState: "SETTLED",
        failureReason: null,
        createdAt: "2026-03-29T11:00:00.000Z",
        latestPaymentAttempt: {
          id: "attempt-2",
          rail: "X402",
          status: "CONFIRMED",
          payerWalletAddress: null,
          currency: "JPYC",
          amount: "80",
          txHash:
            "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          payeeWalletAddress: null,
          failureReason: null,
          createdAt: "2026-03-29T11:00:00.000Z",
          confirmedAt: "2026-03-29T12:30:00.000Z",
        },
      },
    ],
    recentBudgetTransactions: [],
    recentFundingEvidences: [],
    recentPaymentAttemptEvents: [],
    reconciliation: {
      pendingX402Count: 1,
      pendingX402Amount: "100",
      oldestPendingX402CreatedAt: "2026-03-29T12:00:00.000Z",
      pendingX402DeliveryStatus: "ACTIVE",
      pendingX402DeliveryHint: "connector callback 待ちの範囲です。",
      latestPendingX402EventAt: null,
      latestPendingX402EventSource: null,
      latestPendingX402EventType: null,
      failedX402Count: 0,
      failedX402Amount: "0",
      unmatchedFundingEvidenceCount: 0,
      unmatchedFundingEvidenceAmount: "0",
      latestConfirmedX402At: "2026-03-29T12:30:00.000Z",
      recoveryCount: 0,
      latestRecoveryLabel: null,
      latestRecoverySourceLabel: null,
      latestRecoveryCreatedAt: null,
      recoveryConnectorCount: 0,
      recoveryOwnerReviewCount: 0,
      recoveryBillingSystemCount: 0,
      requiresAttention: true,
    },
  });

  assert.equal(timeline.length, 2);
  assert.equal(timeline[0]?.paymentAttemptId, "attempt-2");
  assert.equal(timeline[0]?.status, "CONFIRMED");
  assert.equal(timeline[1]?.paymentAttemptId, "attempt-1");
  assert.equal(timeline[1]?.status, "PENDING");
});
